#!/usr/bin/env bash

set -e -o pipefail

GIT_ROOT=$(git rev-parse --show-toplevel)

source "${GIT_ROOT}/components/_includes.sh"

export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:/usr/local/go/bin

CMD=$1

case $CMD in
  all)
    setup_pre
    setup_fish
    setup_git
    setup_rust
    setup_golang
    setup_docker
    setup_vim
    setup_bat
    install_utilities
    ;;
  utilities)
    install_utilities
    ;;
  golang)
    setup_golang
    ;;
  *)
    echo "Usage: $0 all | golang | utilities"
    exit 1
    ;;
esac
