#!/usr/bin/env bash

set -euo pipefail

GIT_ROOT=$(git rev-parse --show-toplevel)

source "${GIT_ROOT}/components/_includes.sh"

export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:/usr/local/go/bin

function usage() {
  echo "Usage: $0 all | prerequisites | utilities | golang | rust | fish | git | docker | vim | bat"
  exit 1
}

function main() {
  local -r cmd=$1

  case $cmd in
    all)
      prerequisites::install
      fish::install
      rust::install
      golang::install
      docker::install
      vim::install
      utilities::install

      git::setup
      bat::setup
      ;;
    prerequisites)
      prerequisites::install
      ;;
    utilities)
      utilities::install
      ;;
    golang)
      golang::install
      ;;
    rust)
      rust::install
      ;;
    fish)
      fish::install
      ;;
    git)
      git::setup
      ;;
    docker)
      docker::install
      ;;
    vim)
      vim::install
      ;;
    bat)
      bat::setup
      ;;
    *)
      usage
      ;;
  esac
}

if [[ $# -eq 0 ]] || [[ $1 == "help" ]]; then
  usage
fi

main "$@"
